# Generated by Django 2.1.15 on 2021-08-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnwers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pidit', models.CharField(max_length=10, null=True)),
                ('answer', models.CharField(max_length=10)),
                ('question', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=10)),
            ],
        ),
    ]
