# Generated by Django 3.0.6 on 2020-08-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200826_1258'),
        ('home', '0010_delete_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='lang',
        ),
        migrations.DeleteModel(
            name='SettingLang',
        ),
    ]
