# Generated by Django 3.0.6 on 2020-08-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
