# Generated by Django 3.0.6 on 2020-08-31 14:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200830_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Title', models.CharField(blank=True, max_length=10)),
                ('sub_title', models.CharField(blank=True, max_length=5)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('link_type', models.CharField(choices=[('Url', 'Url'), ('Keywords', 'Keywords')], max_length=10)),
                ('search_keywords', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('url', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
