# Generated by Django 3.0.6 on 2020-08-31 14:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200831_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link_type',
            field=models.CharField(choices=[('Url', 'Url'), ('Keywords', 'Keywords')], max_length=100),
        ),
        migrations.AlterField(
            model_name='banner',
            name='search_keywords',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sub_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
