# Generated by Django 3.0.6 on 2020-09-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200831_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='in_charge',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='out_charge',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
