# Generated by Django 3.0.6 on 2020-09-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200903_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='fax',
        ),
        migrations.AddField(
            model_name='setting',
            name='link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
