# Generated by Django 2.1.15 on 2021-08-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_questionanwers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanwers',
            name='answer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='questionanwers',
            name='pidit',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='questionanwers',
            name='question',
            field=models.CharField(max_length=1000),
        ),
    ]
