# Generated by Django 2.2 on 2021-08-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210818_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pidit', models.CharField(max_length=1000, null=True)),
                ('image', models.ImageField(null=True, upload_to='category/')),
            ],
        ),
    ]
